import React, { useState } from "react";
import { Plus, Check, KeyRound, Download, LinkIcon, AlertTriangle, Bell, Inbox, CircleCheck, ArrowRight, Upload } from "./icons";
import {
  useToast, Pill, KPI, Card, PageHeader, PrimaryButton, SecondaryButton, Table, Td, Tabs, Field, inputCls, KV, Note, Toggle
} from "./ui";
import { STATUS_BG, REPORTS, REPORT_RUNS, ALERTS, ALERT_INBOX, USERS, AUDIT } from "./data";

// ============ REPORTS ============
export function ReportsView({ clientName }) {
  const [tab, setTab] = useState("defs");
  const showToast = useToast();
  return (
    <div>
      <PageHeader title={`Reports — ${clientName} (Sandbox)`} subtitle="Generated by the product, with an evidence link on every violation row. No Excel assembly."
        action={<PrimaryButton onClick={() => showToast("Pick a template to schedule a report.", "info")}><Plus className="w-4 h-4" /> Schedule report</PrimaryButton>} />
      <Card>
        <Tabs value={tab} onChange={setTab} tabs={[{ id: "defs", label: "Scheduled reports", count: REPORTS.length }, { id: "runs", label: "Repository", count: REPORT_RUNS.length }, { id: "library", label: "Template library", count: 5 }]} />
        {tab === "defs" && (
          <Table columns={["Report name", "Template", "Schedule", "Recipients", "Delivery", "Last run", "Format", "Visibility"]}>
            {REPORTS.map((r) => (
              <tr key={r.name} className="hover:bg-brand-beige/20">
                <Td className="font-semibold">{r.name}</Td><Td className="text-brand-taupe">{r.template}</Td><Td className="text-brand-taupe whitespace-nowrap">{r.freq}</Td><Td className="text-brand-taupe">{r.recipients}</Td>
                <Td><div className="flex gap-1 flex-wrap">{r.destinations.map((d) => <Pill key={d} text={d} tone={d === "SFTP" ? "bg-blue-50 text-blue-700 border-blue-200" : undefined} />)}</div></Td>
                <Td className="text-brand-taupe whitespace-nowrap">{r.lastRun}</Td><Td><Pill text={r.format} /></Td><Td className="text-brand-taupe">{r.visibility}</Td>
              </tr>
            ))}
          </Table>
        )}
        {tab === "runs" && (
          <Table columns={["Report", "Period", "Generated", "Rows", "Rule set", "Delivery", "Data quality", ""]}>
            {REPORT_RUNS.map((r, i) => (
              <tr key={i} className="hover:bg-brand-beige/20">
                <Td className="font-semibold">{r.name}</Td><Td className="text-brand-taupe">{r.period}</Td><Td className="text-brand-taupe whitespace-nowrap">{r.generated}</Td><Td>{r.rows}</Td><Td className="text-brand-taupe">{r.ruleSet}</Td>
                <Td><Pill text={r.delivery} tone={STATUS_BG.Delivered} /></Td>
                <Td>{r.quality === "OK" ? <span className="text-emerald-700 text-xs font-semibold">OK</span> : <span className="text-amber-700 text-xs font-semibold inline-flex items-center gap-1"><AlertTriangle className="w-3.5 h-3.5" />{r.quality}</span>}</Td>
                <Td><button onClick={() => showToast("Download starts in the real portal.", "info")} className="text-xs text-brand-copper hover:underline cursor-pointer inline-flex items-center gap-1"><Download className="w-3.5 h-3.5" />File</button></Td>
              </tr>
            ))}
          </Table>
        )}
        {tab === "library" && (
          <>
            <Table columns={["Template", "Type", "Parameters", "Accounts using", "Last used", ""]}>
              {[["Listing MAP Report", "MAP", "timeframe · listing states · row cap", 41, "Sep 21", ""], ["Monthly Trend", "Trend", "month · split by classification", 38, "Sep 01", ""], ["Seller Detail", "Seller", "seller set · timeframe", 17, "Sep 21", ""], ["Enforcement Summary", "Enforcement", "timeframe · case states", 9, "Sep 19", ""], ["Listing Extended Data", "Other", "timeframe · fields", 0, "Mar 02", "Unused 6 months — retire?"]].map((r) => (
                <tr key={r[0]}><Td className="font-semibold">{r[0]}</Td><Td className="text-brand-taupe">{r[1]}</Td><Td className="text-brand-taupe">{r[2]}</Td><Td className="tabular-nums">{r[3]}</Td><Td className="text-brand-taupe">{r[4]}</Td><Td className="text-amber-700 text-[11px] font-semibold">{r[5]}</Td></tr>
              ))}
            </Table>
            <div className="mt-3"><Note>Templates are the only path to a report: typed parameters, versioned, with adoption counts. No hand-edited SQL behind the UI.</Note></div>
          </>
        )}
      </Card>
    </div>
  );
}

// ============ ALERTS ============
export function AlertsView({ clientName }) {
  const [tab, setTab] = useState("inbox");
  const [on, setOn] = useState(() => ALERTS.map((a) => a.on));
  return (
    <div>
      <PageHeader title={`Alerts — ${clientName} (Sandbox)`} subtitle="Deduplicated: one alert per change, not one per crawl." action={<PrimaryButton><Plus className="w-4 h-4" /> Add rule</PrimaryButton>} />
      <Card>
        <Tabs value={tab} onChange={setTab} tabs={[{ id: "inbox", label: "Inbox", count: ALERT_INBOX.length }, { id: "rules", label: "Alert rules", count: ALERTS.length }]} />
        {tab === "inbox" && (
          <div className="divide-y divide-brand-beige">
            {ALERT_INBOX.map((a, i) => (
              <div key={i} className="py-3 flex items-start gap-3">
                <Pill text={a.level} tone={a.level === "Severe" ? "bg-red-50 text-red-700 border-red-200" : a.level === "Health" ? STATUS_BG.Degraded : STATUS_BG["Notice sent"]} />
                <div className="flex-1 text-sm text-brand-charcoal">{a.text}</div>
                <div className="text-xs text-brand-taupe whitespace-nowrap">{a.time}</div>
              </div>
            ))}
          </div>
        )}
        {tab === "rules" && (
          <Table columns={["Alert", "Trigger", "Channel", "Recipients", "On"]}>
            {ALERTS.map((a, i) => (
              <tr key={a.name}><Td className="font-semibold">{a.name}</Td><Td className="text-brand-taupe">{a.condition}</Td><Td className="text-brand-taupe">{a.channel}</Td><Td className="text-brand-taupe">{a.recipients}</Td><Td><Toggle on={on[i]} onChange={(v) => setOn(on.map((x, j) => (j === i ? v : x)))} /></Td></tr>
            ))}
          </Table>
        )}
      </Card>
    </div>
  );
}

// ============ SETTINGS (account configuration) ============
export function SettingsView({ clientName }) {
  const showToast = useToast();
  return (
    <div>
      <PageHeader title={`Settings — ${clientName} (Sandbox)`} subtitle="Account process lives here as data — not in a wiki page or someone's laptop." action={<PrimaryButton onClick={() => showToast("Settings saved. Change recorded in audit log.")}><Check className="w-4 h-4" /> Save changes</PrimaryButton>} />
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card title="Account">
          <div className="space-y-3 text-sm">
            <Field label="Account name"><input id="set-name" className={inputCls} defaultValue={`${clientName} Electronics USA`} /></Field>
            <div className="grid grid-cols-2 gap-3"><Field label="Regions in scope"><input id="set-regions" className={inputCls} defaultValue="United States" /></Field><Field label="Currency / timezone"><input id="set-cur" className={inputCls} defaultValue="USD · America/New_York" /></Field></div>
            <div className="grid grid-cols-2 gap-3"><Field label="Contract"><input id="set-contract" className={inputCls} defaultValue="Oct 01, 2026 – Sep 30, 2027" /></Field><Field label="Seats"><input id="set-seats" className={inputCls} defaultValue="8" /></Field></div>
          </div>
        </Card>
        <Card title="Violation defaults">
          <div className="space-y-3 text-sm">
            <div className="grid grid-cols-3 gap-3"><Field label="MAP tolerance"><input id="set-tol" className={inputCls} defaultValue="2%" /></Field><Field label="Min. depth"><input id="set-depth" className={inputCls} defaultValue="$1" /></Field><Field label="Grace window"><input id="set-grace" className={inputCls} defaultValue="0 h" /></Field></div>
            <div className="flex justify-between items-center"><span className="text-xs text-brand-taupe">Brand approval required before notices</span><Toggle on onChange={() => {}} /></div>
            <div className="flex justify-between items-center"><span className="text-xs text-brand-taupe">Brand users can see Needs-review items</span><Toggle on={false} onChange={() => {}} /></div>
          </div>
        </Card>
        <Card title="Match confidence thresholds">
          <div className="space-y-3 text-xs">
            <div className="h-3 rounded-full overflow-hidden flex"><div className="bg-red-300" style={{ width: "60%" }} /><div className="bg-amber-300" style={{ width: "30%" }} /><div className="bg-emerald-400" style={{ width: "10%" }} /></div>
            <div className="flex justify-between text-brand-taupe"><span>0</span><span>Auto-exclude &lt; 60</span><span>Review 60–89</span><span>Auto-include ≥ 90</span><span>100</span></div>
            <KV k="QA sample of auto decisions" v="5%" />
            <KV k="Auto-include precision (last 30d)" v="99.2%" />
          </div>
        </Card>
        <Card title="Report process & delivery">
          <div className="space-y-2.5 text-xs">
            <KV k="Weekly report due" v="Monday 08:00 ET" />
            <KV k="Distribution list" v="LG MAP Room (4)" />
            <KV k="Escalation contact" v="channel@lg.com" />
            <KV k="SFTP destination" v={<span className="inline-flex items-center gap-1"><KeyRound className="w-3.5 h-3.5" />sftp.lg-partner.example:/mirethos · vaulted</span>} />
            <KV k="Slack" v="#lg-map-alerts · connected" />
          </div>
        </Card>
      </div>
    </div>
  );
}

// ============ USERS ============
export function UsersView({ clientName }) {
  return (
    <div>
      <PageHeader title={`Users & Access — ${clientName} (Sandbox)`} action={<PrimaryButton><Plus className="w-4 h-4" /> Invite user</PrimaryButton>} />
      <Card>
        <Table columns={["User", "Role", "Can", "Last active", "Status"]}>
          {USERS.map((u) => (
            <tr key={u.name}><Td className="font-semibold">{u.name}</Td><Td>{u.role}</Td><Td className="text-brand-taupe">{u.access}</Td><Td className="text-brand-taupe">{u.lastActive}</Td><Td><Pill text={u.status} tone={STATUS_BG.Active} /></Td></tr>
          ))}
        </Table>
        <div className="mt-3"><Note>Brand users only ever see their own account. Mirethos support access is logged.</Note></div>
      </Card>
    </div>
  );
}

// ============ AUDIT ============
export function AuditLogView({ clientName }) {
  return (
    <div>
      <PageHeader title={`Audit Log — ${clientName} (Sandbox)`} subtitle="Append-only. Every change records who (person, rule or model version), when, and before → after." />
      <Card>
        <Table columns={["Time", "Actor", "Action", "Before", "After"]}>
          {AUDIT.map((r, i) => (
            <tr key={i}><Td className="text-brand-taupe whitespace-nowrap">{r.time}</Td><Td className="font-semibold">{r.user}</Td><Td>{r.action}</Td><Td className="text-brand-taupe">{r.before}</Td><Td className="text-brand-charcoal font-medium">{r.after}</Td></tr>
          ))}
        </Table>
      </Card>
    </div>
  );
}

// ============ ONBOARDING (guided new-account flow) ============
const STEPS = [
  { t: "Account", d: "Brand, regions, currency, contract, users and roles." },
  { t: "Catalogue", d: "Import SKUs with identifiers. Dry-run diff before commit." },
  { t: "MAP & policy", d: "Import MAP with effective dates, promo windows and the policy PDF." },
  { t: "Sellers", d: "Authorised reseller list and contacts." },
  { t: "Sources & terms", d: "Subscribe sources, generate terms from catalogue, check the cost estimate." },
  { t: "Rules & baseline", d: "Start from default rule templates, run a baseline crawl, review matches." },
  { t: "Reports & alerts", d: "Subscribe to templates, set recipients and delivery. Go live." },
];
export function OnboardingView({ onDone }) {
  const [step, setStep] = useState(1);
  const showToast = useToast();
  return (
    <div className="min-h-screen flex items-center justify-center bg-brand-ivory font-sans p-4">
      <div className="max-w-3xl w-full bg-brand-white border border-brand-beige rounded-xl p-6 shadow-md">
        <div className="text-xs font-semibold text-brand-taupe uppercase tracking-wider">New account</div>
        <h2 className="text-lg font-bold text-brand-charcoal mb-5">Set up Citizen Watch America</h2>
        <div className="grid grid-cols-1 md:grid-cols-[220px_1fr] gap-6">
          <ol className="space-y-1">
            {STEPS.map((s, i) => (
              <li key={s.t}>
                <button onClick={() => setStep(i)} className={`w-full text-left flex items-center gap-2 px-2.5 py-2 rounded-lg text-sm cursor-pointer ${i === step ? "bg-brand-beige font-semibold text-brand-charcoal" : "text-brand-taupe"}`}>
                  <span className={`w-5 h-5 rounded-full text-[10px] flex items-center justify-center border ${i < step ? "bg-brand-copper border-brand-copper text-brand-white" : "border-brand-beige"}`}>{i < step ? "✓" : i + 1}</span>{s.t}
                </button>
              </li>
            ))}
          </ol>
          <div>
            <h3 className="text-sm font-bold text-brand-charcoal">{STEPS[step].t}</h3>
            <p className="text-xs text-brand-taupe mb-4">{STEPS[step].d}</p>
            {step === 1 ? (
              <div className="space-y-3">
                <div className="border-2 border-dashed border-brand-beige rounded-xl p-6 text-center text-xs text-brand-taupe"><Upload className="w-5 h-5 mx-auto mb-2" />Citizen_catalogue_2026.xlsx · 412 rows</div>
                <div className="flex gap-3 flex-wrap"><KPI label="New products" value="398" /><KPI label="With UPC / MPN" value="97%" /><KPI label="Missing identifiers" value="14" sub="add a known URL instead" subTone="text-amber-700" /></div>
              </div>
            ) : (
              <Note>Each step writes real configuration to the account. When all steps are done, the account is complete — no handover call, no wiki page.</Note>
            )}
            <div className="flex justify-between mt-6">
              <SecondaryButton onClick={onDone}>Save & exit</SecondaryButton>
              {step < STEPS.length - 1
                ? <PrimaryButton onClick={() => setStep(step + 1)}>Continue <ArrowRight className="w-4 h-4" /></PrimaryButton>
                : <PrimaryButton onClick={() => { showToast("Account live. Baseline crawl scheduled."); onDone(); }}><CircleCheck className="w-4 h-4" /> Go live</PrimaryButton>}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
