// Reports (docs/reference/prototype-src/views_admin.jsx ReportsView): scheduled reports, the
// repository of generated runs (rule set and data-quality note on each), and the template library
// with adoption counts. Templates are the only path to a report.
import React, { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Copy, Download, KeyRound, Play, Plus, ShieldCheck } from "lucide-react";
import { api } from "../api/client.js";
import { Card, Field, inputCls, Modal, Note, PageHeader, Pill, PrimaryButton, SecondaryButton, Table, Tabs, Td, Toggle } from "../ui.jsx";
import { formatDay } from "../format.js";
import { attempt, formatWhen, useWorkspace } from "../workspace.js";

const GREEN = "bg-emerald-50 text-emerald-700 border-emerald-200";
const AMBER = "bg-amber-50 text-amber-700 border-amber-200";
const RED = "bg-red-50 text-red-700 border-red-200";
const BLUE = "bg-blue-50 text-blue-700 border-blue-200";
const DELIVERY_TONE = { delivered: GREEN, sent: GREEN, logged: BLUE, failed: RED };
const RUN_TONE = { done: GREEN, awaiting_pdf: AMBER, queued: AMBER, failed: RED };
const RUN_LABEL = { done: "Done", awaiting_pdf: "PDF within the hour", queued: "Queued", failed: "Failed" };
const TIMEFRAME_LABEL = { previous_week: "Previous week (Mon–Sun)", last_7_days: "Last 7 days", last_30_days: "Last 30 days", previous_month: "Previous month" };
const CADENCES = [
  ["0 8 * * 1", "Weekly · Monday 08:00"],
  ["0 8 * * *", "Daily · 08:00"],
  ["0 7 1 * *", "Monthly · 1st at 07:00"],
  ["manual", "Manual only (Run now)"],
];
const DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

function cadenceText(c) {
  const known = CADENCES.find(([v]) => v === c);
  if (known) return known[1];
  const m = /^(\d+) (\d+) (\*|\d+) \* (\*|\d)$/.exec(c || "");
  if (m) {
    const t = `${m[2].padStart(2, "0")}:${m[1].padStart(2, "0")}`;
    if (m[3] !== "*") return `Monthly · day ${m[3]} at ${t}`;
    if (m[4] !== "*") return `Weekly · ${DAYS[Number(m[4])]} ${t}`;
    return `Daily · ${t}`;
  }
  return c;
}
const deliveryPills = (d) => [d.email !== false && "Email", d.hosted !== false && "Hosted link", d.sftp && "SFTP"].filter(Boolean);

export function ReportsView() {
  const { client, can, showToast } = useWorkspace();
  const [tab, setTab] = useState("defs");
  const [defs, setDefs] = useState([]);
  const [runs, setRuns] = useState([]);
  const [templates, setTemplates] = useState([]);
  const [editing, setEditing] = useState(null); // {} new, or a definition
  const [openRun, setOpenRun] = useState(null);
  const writable = can("reports.write");

  const load = useCallback(async () => {
    setDefs((await attempt(showToast, () => api.reportDefinitions(client))) ?? []);
    setRuns((await attempt(showToast, () => api.reportRuns(client))) ?? []);
    setTemplates((await attempt(showToast, () => api.reportTemplates(client))) ?? []);
  }, [client, showToast]);
  useEffect(() => { attempt(showToast, load); }, [load, showToast]);

  const runNow = async (d) => {
    const r = await attempt(showToast, () => api.runReportDefinition(client, d.id));
    if (r) { showToast(`${r.code} generated. The hosted page and CSV are ready; the PDF follows within the hour.`); setTab("runs"); load(); }
  };
  const runOnce = async (t) => {
    const r = await attempt(showToast, () => api.runReport(client, { templateCode: t.code, params: {} }));
    if (r) { showToast(`${r.code} generated with default settings. The PDF follows within the hour.`); setTab("runs"); load(); }
  };
  const setActive = async (d, active) => {
    if (await attempt(showToast, () => api.updateReportDefinition(client, d.id, { active }))) load();
  };

  return (
    <div>
      <PageHeader title={`Reports — ${client.name} (${client.status})`} subtitle="Generated by the product, with an evidence link on every violation row. No Excel assembly."
        action={writable && <PrimaryButton onClick={() => setEditing({})}><Plus className="w-4 h-4" /> Schedule report</PrimaryButton>} />
      <Card>
        <Tabs value={tab} onChange={setTab} tabs={[{ id: "defs", label: "Scheduled reports", count: defs.length }, { id: "runs", label: "Repository", count: runs.length }, { id: "library", label: "Template library", count: templates.length }]} />
        {tab === "defs" && (defs.length ? (
          <Table columns={["Report name", "Template", "Schedule", "Recipients", "Delivery", "Last run", "Visibility", "Active", ""]}>
            {defs.map((d) => (
              <tr key={d.id} className="hover:bg-brand-beige/20">
                <Td className="font-semibold">{writable ? <button className="text-left hover:underline cursor-pointer" onClick={() => setEditing(d)}>{d.name}</button> : d.name}</Td>
                <Td className="text-brand-taupe">{d.template}</Td>
                <Td className="text-brand-taupe whitespace-nowrap">{cadenceText(d.cadence)}{d.next_run ? <div className="text-[10px]">next {formatWhen(d.next_run)}</div> : null}</Td>
                <Td className="text-brand-taupe">{d.recipients.join(", ") || "—"}</Td>
                <Td><div className="flex gap-1 flex-wrap">{deliveryPills(d.destinations).map((x) => <Pill key={x} text={x} tone={x === "SFTP" ? BLUE : undefined} />)}</div></Td>
                <Td className="text-brand-taupe whitespace-nowrap">{d.last_run ? `RPT-${String(d.last_run.seq).padStart(4, "0")} · ${formatWhen(d.last_run.created_at)}` : "—"}</Td>
                <Td className="text-brand-taupe">{d.visibility}</Td>
                <Td><Toggle on={d.active} onChange={(v) => setActive(d, v)} disabled={!writable} /></Td>
                <Td>{writable && <button onClick={() => runNow(d)} className="text-xs text-brand-copper hover:underline cursor-pointer inline-flex items-center gap-1 whitespace-nowrap"><Play className="w-3.5 h-3.5" />Run now</button>}</Td>
              </tr>
            ))}
          </Table>
        ) : <div className="text-sm text-brand-taupe py-6 text-center">No scheduled reports yet.{writable ? " Use Schedule report, or run a template once from the library." : ""}</div>)}
        {tab === "runs" && (runs.length ? (
          <Table columns={["Report", "Period", "Generated", "Rows", "Rule set", "Delivery", "Data quality", ""]}>
            {runs.map((r) => (
              <tr key={r.id} className="hover:bg-brand-beige/20">
                <Td className="font-semibold"><span className="text-brand-copper mr-1.5">{r.code}</span>{r.name}<div className="text-[10px] text-brand-taupe font-normal">{r.template}</div></Td>
                <Td className="text-brand-taupe whitespace-nowrap">{formatDay(r.period_from)} – {formatDay(new Date(new Date(r.period_to).getTime() - 1).toISOString())}</Td>
                <Td className="text-brand-taupe whitespace-nowrap">{formatWhen(r.created_at)}<div><Pill text={RUN_LABEL[r.status]} tone={RUN_TONE[r.status]} /></div></Td>
                <Td>{r.rows ?? "—"}</Td>
                <Td className="text-brand-taupe">{(r.rule_set ?? []).map((x) => `${x.code} v${x.version}`).join(", ") || "—"}</Td>
                <Td><div className="flex gap-1 flex-wrap">{r.deliveries.length ? r.deliveries.map((d, i) => <Pill key={i} text={`${d.channel} ${d.status}`} tone={DELIVERY_TONE[d.status]} />) : <span className="text-brand-taupe text-xs">{r.status === "done" ? "—" : "after the PDF"}</span>}</div></Td>
                <Td>{r.quality_note
                  ? <span className="text-amber-700 text-xs font-semibold inline-flex items-start gap-1" title={r.quality_note}><AlertTriangle className="w-3.5 h-3.5 shrink-0" />{r.quality_note.replace(/^Data quality: /, "").slice(0, 60)}{r.quality_note.length > 74 ? "…" : ""}</span>
                  : r.status === "failed" ? <span className="text-red-700 text-xs" title={r.error}>Failed</span> : <span className="text-emerald-700 text-xs font-semibold">OK</span>}</Td>
                <Td>{r.status !== "queued" && r.status !== "failed" && <button onClick={() => setOpenRun(r.id)} className="text-xs text-brand-copper hover:underline cursor-pointer inline-flex items-center gap-1">Open</button>}</Td>
              </tr>
            ))}
          </Table>
        ) : <div className="text-sm text-brand-taupe py-6 text-center">No reports generated yet.</div>)}
        {tab === "library" && (
          <>
            <Table columns={["Template", "Type", "Parameters", "Accounts using", "Used here", "Last used", ""]}>
              {templates.map((t) => (
                <tr key={t.code}>
                  <Td className="font-semibold">{t.name} <span className="text-[10px] text-brand-taupe font-normal">v{t.version}</span><div className="text-[11px] text-brand-taupe font-normal">{t.description}</div></Td>
                  <Td className="text-brand-taupe">{t.type}</Td>
                  <Td className="text-brand-taupe">{t.params.map((p) => p.label.toLowerCase()).join(" · ")}</Td>
                  <Td className="tabular-nums">{t.accounts}</Td>
                  <Td className="tabular-nums">{t.used_here}</Td>
                  <Td className="text-brand-taupe">{t.last_used ? formatDay(t.last_used) : "never"}</Td>
                  <Td className="whitespace-nowrap">{writable && <span className="flex gap-3">
                    <button onClick={() => setEditing({ template_code: t.code })} className="text-xs text-brand-copper hover:underline cursor-pointer">Schedule</button>
                    {t.code !== "seller_detail" && <button onClick={() => runOnce(t)} className="text-xs text-brand-copper hover:underline cursor-pointer">Run once</button>}
                  </span>}</Td>
                </tr>
              ))}
            </Table>
            <div className="mt-3"><Note>Templates are the only path to a report: typed parameters, versioned, with adoption counts. No hand-edited SQL behind the UI.</Note></div>
          </>
        )}
      </Card>
      {editing && <DefinitionModal def={editing} templates={templates} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); setTab("defs"); load(); }} />}
      {openRun && <RunModal runId={openRun} onClose={() => setOpenRun(null)} />}
    </div>
  );
}

function RunModal({ runId, onClose }) {
  const { client, can, showToast } = useWorkspace();
  const [r, setR] = useState(null);
  useEffect(() => { attempt(showToast, () => api.reportRun(client, runId)).then((x) => setR(x ?? null)); }, [client, runId, showToast]);
  const copyLink = async () => {
    const l = await attempt(showToast, () => api.reportRunLink(client, runId));
    if (!l) return;
    try { await navigator.clipboard.writeText(l.url); showToast(`Hosted link copied. It expires ${formatDay(l.expiresAt)}.`); }
    catch { showToast(`Copying was blocked by the browser. The link: ${l.url}`, "info"); }
  };
  return (
    <Modal open onClose={onClose} title={r ? `${r.code} · ${r.name}` : "Loading…"} width="w-[64rem]">
      {r && (
        <div className="space-y-3">
          <div className="flex gap-3 items-center flex-wrap text-xs">
            {r.files.map((f) => f.url
              ? <a key={f.kind} href={f.url} download={f.fileName} className="text-brand-copper hover:underline inline-flex items-center gap-1"><Download className="w-3.5 h-3.5" />{f.kind.toUpperCase()}</a>
              : <span key={f.kind} className="text-brand-taupe">{f.kind.toUpperCase()} (sample)</span>)}
            {!r.files.some((f) => f.kind === "pdf") && <span className="text-amber-700">The PDF is printed by the hourly reports run.</span>}
            {can("reports.write") && <button onClick={copyLink} className="text-brand-copper hover:underline inline-flex items-center gap-1 cursor-pointer ml-auto"><Copy className="w-3.5 h-3.5" />Copy hosted link</button>}
          </div>
          {r.html ? <iframe title={r.name} srcDoc={r.html} sandbox="allow-popups allow-popups-to-escape-sandbox" className="w-full h-[70vh] border border-brand-beige rounded-lg bg-white" /> : <Note>Not generated yet.</Note>}
        </div>
      )}
    </Modal>
  );
}

function ParamField({ p, value, onChange, sellers }) {
  if (p.type === "enum") {
    return <select className={inputCls} value={value ?? p.default} onChange={(e) => onChange(e.target.value)}>{p.values.map((v) => <option key={v} value={v}>{TIMEFRAME_LABEL[v] ?? v}</option>)}</select>;
  }
  if (p.type === "multi") {
    const cur = value ?? p.default;
    return <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs">{p.values.map((v) => (
      <label key={v} className="inline-flex items-center gap-1.5"><input type="checkbox" checked={cur.includes(v)} onChange={() => onChange(cur.includes(v) ? cur.filter((x) => x !== v) : [...cur, v])} />{v}</label>
    ))}</div>;
  }
  if (p.type === "int") return <input type="number" className={inputCls} min={p.min} max={p.max} value={value ?? p.default} onChange={(e) => onChange(Number(e.target.value))} />;
  if (p.type === "bool") return <Toggle on={value ?? p.default} onChange={onChange} />;
  if (p.type === "month") {
    return <input className={inputCls} value={value ?? p.default} onChange={(e) => onChange(e.target.value)} placeholder="previous, or YYYY-MM" />;
  }
  if (p.type === "sellers") {
    const cur = value ?? [];
    return (
      <div className="max-h-40 overflow-y-auto border border-brand-beige rounded-lg p-2 text-xs space-y-1">
        {sellers.length ? sellers.map((s) => (
          <label key={s.id} className="flex items-center gap-1.5"><input type="checkbox" checked={cur.includes(s.id)} onChange={() => onChange(cur.includes(s.id) ? cur.filter((x) => x !== s.id) : [...cur, s.id])} />{s.name} <span className="text-brand-taupe">({s.source})</span></label>
        )) : <span className="text-brand-taupe">No sellers yet.</span>}
      </div>
    );
  }
  return null;
}

function DefinitionModal({ def, templates, onClose, onSaved }) {
  const { client, can, showToast } = useWorkspace();
  const isNew = !def.id;
  const [templateCode, setTemplateCode] = useState(def.template_code ?? "listing_map");
  const [name, setName] = useState(def.name ?? "");
  const [params, setParams] = useState(def.params ?? {});
  const [cadence, setCadence] = useState(def.cadence ?? "0 8 * * 1");
  const [custom, setCustom] = useState(def.cadence && !CADENCES.some(([v]) => v === def.cadence));
  const [timezone, setTimezone] = useState(def.timezone ?? "America/New_York");
  const [recipients, setRecipients] = useState((def.recipients ?? []).join(", "));
  const [dest, setDest] = useState(def.destinations ?? { email: true, hosted: true });
  const [visibility, setVisibility] = useState(def.visibility ?? "Account");
  const [creds, setCreds] = useState([]);
  const [sellers, setSellers] = useState([]);
  const [test, setTest] = useState(null);
  const tpl = templates.find((t) => t.code === templateCode);

  useEffect(() => {
    if (can("credentials.read")) attempt(showToast, () => api.credentials(client)).then((c) => setCreds((c ?? []).filter((x) => x.kind === "sftp")));
    if (templateCode === "seller_detail" && can("sellers.read")) attempt(showToast, () => api.sellers(client)).then((s) => setSellers(s ?? []));
  }, [client, can, showToast, templateCode]);

  const sftp = dest.sftp ?? null;
  const setSftp = (patch) => { setDest({ ...dest, sftp: { port: 22, folder: "", ...(sftp ?? {}), ...patch } }); setTest(null); };
  const runTest = async () => {
    const r = await attempt(showToast, () => api.sftpTest(client, { credentialId: sftp.credentialId, host: sftp.host, port: Number(sftp.port) || 22, folder: sftp.folder ?? "", hostKey: sftp.hostKey || undefined }));
    if (r) setTest(r);
  };

  const save = async (e) => {
    e.preventDefault();
    const body = {
      name: name.trim(), templateCode, params, cadence, timezone, visibility,
      recipients: recipients.split(/[,\s]+/).map((x) => x.trim()).filter(Boolean),
      destinations: { email: dest.email !== false, hosted: dest.hosted !== false, sftp: sftp ? { ...sftp, port: Number(sftp.port) || 22 } : null },
    };
    const r = await attempt(showToast, () => (isNew ? api.createReportDefinition(client, body) : api.updateReportDefinition(client, def.id, body)));
    if (r) { showToast(isNew ? `"${body.name}" scheduled: ${cadenceText(cadence)}.` : `"${body.name}" saved.`); onSaved(); }
  };

  return (
    <Modal open onClose={onClose} title={isNew ? "Schedule report" : `Edit "${def.name}"`} width="w-[48rem]">
      <form className="space-y-4" onSubmit={save}>
        <div className="grid grid-cols-2 gap-3">
          <Field label="Report name *"><input className={inputCls} value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Weekly MAP report" /></Field>
          <Field label="Template">
            <select className={inputCls} value={templateCode} onChange={(e) => { setTemplateCode(e.target.value); setParams({}); }} disabled={!isNew}>
              {templates.map((t) => <option key={t.code} value={t.code}>{t.name}</option>)}
            </select>
          </Field>
        </div>
        {tpl && <div className="grid grid-cols-2 gap-3">{tpl.params.map((p) => (
          <Field key={p.key} label={p.label}><ParamField p={p} value={params[p.key]} sellers={sellers} onChange={(v) => setParams({ ...params, [p.key]: v })} /></Field>
        ))}</div>}
        <div className="grid grid-cols-2 gap-3">
          <Field label="Schedule">
            {custom
              ? <input className={inputCls} value={cadence} onChange={(e) => setCadence(e.target.value)} placeholder="cron, e.g. 0 8 * * 1" />
              : <select className={inputCls} value={cadence} onChange={(e) => (e.target.value === "custom" ? setCustom(true) : setCadence(e.target.value))}>
                {CADENCES.map(([v, l]) => <option key={v} value={v}>{l}</option>)}<option value="custom">Custom (cron)…</option>
              </select>}
          </Field>
          <Field label="Timezone"><input className={inputCls} value={timezone} onChange={(e) => setTimezone(e.target.value)} /></Field>
        </div>
        <Field label="Recipients (emails, comma-separated)"><input className={inputCls} value={recipients} onChange={(e) => setRecipients(e.target.value)} placeholder="map-room@brand.com" /></Field>
        <div className="flex gap-5 text-xs flex-wrap items-center">
          <label className="inline-flex items-center gap-1.5"><input type="checkbox" checked={dest.email !== false} onChange={(e) => setDest({ ...dest, email: e.target.checked })} />Email (logged until a provider is set up)</label>
          <label className="inline-flex items-center gap-1.5"><input type="checkbox" checked={dest.hosted !== false} onChange={(e) => setDest({ ...dest, hosted: e.target.checked })} />Hosted link (90 days)</label>
          <label className="inline-flex items-center gap-1.5"><input type="checkbox" checked={!!sftp} onChange={(e) => setDest({ ...dest, sftp: e.target.checked ? { port: 22, folder: "" } : null })} />SFTP</label>
          <span className="ml-auto inline-flex items-center gap-2">Visible to
            <select className={`${inputCls} w-auto`} value={visibility} onChange={(e) => setVisibility(e.target.value)}><option>Account</option><option>Brand users</option></select>
          </span>
        </div>
        {sftp && (
          <Card title="SFTP destination">
            {!creds.length ? <Note tone="bg-amber-50 text-amber-800 border-amber-200">Add an SFTP credential first: Settings → Credentials (kind SFTP, the username, and the password or private key).</Note> : (
              <div className="space-y-3 text-xs">
                <div className="grid grid-cols-3 gap-3">
                  <Field label="Credential"><select className={inputCls} value={sftp.credentialId ?? ""} onChange={(e) => setSftp({ credentialId: e.target.value })}>
                    <option value="">Choose…</option>{creds.map((c) => <option key={c.id} value={c.id}>{c.label} ({c.username})</option>)}
                  </select></Field>
                  <Field label="Host"><input className={inputCls} value={sftp.host ?? ""} onChange={(e) => setSftp({ host: e.target.value.trim() })} placeholder="sftp.brand.com" /></Field>
                  <Field label="Port"><input className={inputCls} type="number" value={sftp.port ?? 22} onChange={(e) => setSftp({ port: e.target.value })} /></Field>
                </div>
                <Field label="Folder"><input className={inputCls} value={sftp.folder ?? ""} onChange={(e) => setSftp({ folder: e.target.value })} placeholder="/incoming/map-intel (empty = home folder)" /></Field>
                <div className="flex items-center gap-3 flex-wrap">
                  <SecondaryButton onClick={runTest} disabled={!sftp.credentialId || !sftp.host}><KeyRound className="w-4 h-4" /> Test connection</SecondaryButton>
                  {sftp.hostKey ? <span className="inline-flex items-center gap-1 text-emerald-700"><ShieldCheck className="w-3.5 h-3.5" />Server key pinned: <span className="font-mono">{sftp.hostKey}</span></span>
                    : <span className="text-brand-taupe">The server's key must be confirmed and pinned before reports are sent.</span>}
                </div>
                {test && (
                  <Note tone={test.ok ? "bg-emerald-50 text-emerald-800 border-emerald-200" : "bg-amber-50 text-amber-800 border-amber-200"}>
                    {test.message}
                    {!test.ok && test.hostKey && !sftp.hostKey && (
                      <div className="mt-2">Check this fingerprint with the brand, then:{" "}
                        <button type="button" className="underline font-semibold cursor-pointer" onClick={() => setSftp({ hostKey: test.hostKey })}>Trust this key</button></div>
                    )}
                  </Note>
                )}
              </div>
            )}
          </Card>
        )}
        <div className="flex justify-end gap-2 border-t border-brand-beige pt-3">
          <SecondaryButton onClick={onClose}>Cancel</SecondaryButton>
          <PrimaryButton type="submit" disabled={!name.trim() || (sftp && !sftp.hostKey)}>{isNew ? "Schedule" : "Save"}</PrimaryButton>
        </div>
        {sftp && !sftp.hostKey && <div className="text-[11px] text-brand-taupe text-right">Test the SFTP connection and trust the server's key to save.</div>}
      </form>
    </Modal>
  );
}
